services:
  - type: web
    name: carbon-market-backend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: PORT
        value: 5000
      - key: MONGO_URI
        value: mongodb+srv://20kidzzz26_db_user:CLtsOCODXpNCvVMP@cluster0.v5cleb2.mongodb.net/?appName=Cluster0
